USE QUANLYBANLE;
GO

IF OBJECT_ID('dbo.SP_GETTAIKHOAN', 'P') IS NOT NULL DROP PROC dbo.SP_GETTAIKHOAN;
GO
CREATE PROC dbo.SP_GETTAIKHOAN
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MATAIKHOAN, USERNAME, PASS, QUYEN
    FROM TAIKHOAN;
END
GO

IF OBJECT_ID('dbo.SP_GETBYIDTAIKHOAN', 'P') IS NOT NULL DROP PROC dbo.SP_GETBYIDTAIKHOAN;
GO
CREATE PROC dbo.SP_GETBYIDTAIKHOAN
    @MATAIKHOAN CHAR(15)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MATAIKHOAN, USERNAME, PASS, QUYEN
    FROM TAIKHOAN
    WHERE MATAIKHOAN = @MATAIKHOAN;
END
GO

IF OBJECT_ID('dbo.SP_DANGNHAP', 'P') IS NOT NULL DROP PROC dbo.SP_DANGNHAP;
GO
CREATE PROC dbo.SP_DANGNHAP
    @USERNAME VARCHAR(50),
    @PASS     VARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MATAIKHOAN, USERNAME, QUYEN
    FROM TAIKHOAN
    WHERE USERNAME = @USERNAME AND PASS = @PASS;
END
GO

IF OBJECT_ID('dbo.SP_THEMTAIKHOAN', 'P') IS NOT NULL DROP PROC dbo.SP_THEMTAIKHOAN;
GO
CREATE PROC dbo.SP_THEMTAIKHOAN
    @MATAIKHOAN CHAR(15),
    @USERNAME   VARCHAR(50),
    @PASS       VARCHAR(200),
    @QUYEN      INT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO TAIKHOAN (MATAIKHOAN, USERNAME, PASS, QUYEN)
    VALUES (@MATAIKHOAN, @USERNAME, @PASS, @QUYEN);
END
GO

IF OBJECT_ID('dbo.SP_SUATAIKHOAN', 'P') IS NOT NULL DROP PROC dbo.SP_SUATAIKHOAN;
GO
CREATE PROC dbo.SP_SUATAIKHOAN
    @MATAIKHOAN CHAR(15),
    @USERNAME   VARCHAR(50),
    @PASS       VARCHAR(200),
    @QUYEN      INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TAIKHOAN
    SET USERNAME = @USERNAME, PASS = @PASS, QUYEN = @QUYEN
    WHERE MATAIKHOAN = @MATAIKHOAN;
END
GO

IF OBJECT_ID('dbo.SP_XOATAIKHOAN', 'P') IS NOT NULL DROP PROC dbo.SP_XOATAIKHOAN;
GO
CREATE PROC dbo.SP_XOATAIKHOAN
    @MATAIKHOAN CHAR(15)
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM TAIKHOAN WHERE MATAIKHOAN = @MATAIKHOAN;
END
GO



USE QUANLYBANLE;
GO

IF OBJECT_ID('dbo.SP_GETNHANVIEN','P') IS NOT NULL DROP PROC dbo.SP_GETNHANVIEN;
GO
CREATE PROC dbo.SP_GETNHANVIEN
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MANV, TENNV, SDT, DIACHI
    FROM NHANVIEN;
END
GO

IF OBJECT_ID('dbo.SP_GETBYIDNHANVIEN','P') IS NOT NULL DROP PROC dbo.SP_GETBYIDNHANVIEN;
GO
CREATE PROC dbo.SP_GETBYIDNHANVIEN
    @MANV CHAR(15)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MANV, TENNV, SDT, DIACHI
    FROM NHANVIEN
    WHERE MANV = @MANV;
END
GO

IF OBJECT_ID('dbo.SP_THEMNHANVIEN','P') IS NOT NULL DROP PROC dbo.SP_THEMNHANVIEN;
GO
CREATE PROC dbo.SP_THEMNHANVIEN
    @MANV   CHAR(15),
    @TENNV  NVARCHAR(50),
    @SDT    VARCHAR(15),
    @DIACHI NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO NHANVIEN(MANV, TENNV, SDT, DIACHI)
    VALUES(@MANV, @TENNV, @SDT, @DIACHI);
END
GO

IF OBJECT_ID('dbo.SP_SUANHANVIEN','P') IS NOT NULL DROP PROC dbo.SP_SUANHANVIEN;
GO
CREATE PROC dbo.SP_SUANHANVIEN
    @MANV   CHAR(15),
    @TENNV  NVARCHAR(50),
    @SDT    VARCHAR(15),
    @DIACHI NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE NHANVIEN
    SET TENNV=@TENNV, SDT=@SDT, DIACHI=@DIACHI
    WHERE MANV=@MANV;
END
GO

IF OBJECT_ID('dbo.SP_XOANHANVIEN','P') IS NOT NULL DROP PROC dbo.SP_XOANHANVIEN;
GO
CREATE PROC dbo.SP_XOANHANVIEN
    @MANV CHAR(15)
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM NHANVIEN WHERE MANV=@MANV;
END
GO

USE QUANLYBANLE;
GO



/* ==== PHIEU NHAP KHO ==== */
IF OBJECT_ID('dbo.SP_GETPHIEUNHAPKHO','P') IS NOT NULL DROP PROC dbo.SP_GETPHIEUNHAPKHO;
GO
CREATE PROC dbo.SP_GETPHIEUNHAPKHO
AS
BEGIN
  SET NOCOUNT ON;
  SELECT MAPHIEUNHAP, MASP, MANCC, MANV, NGAYLAP, THUEVAT FROM PHIEUNHAPKHO;
END
GO

IF OBJECT_ID('dbo.SP_GETBYIDPHIEUNHAPKHO','P') IS NOT NULL DROP PROC dbo.SP_GETBYIDPHIEUNHAPKHO;
GO
CREATE PROC dbo.SP_GETBYIDPHIEUNHAPKHO @MAPHIEUNHAP CHAR(15)
AS
BEGIN
  SET NOCOUNT ON;
  SELECT MAPHIEUNHAP, MASP, MANCC, MANV, NGAYLAP, THUEVAT
  FROM PHIEUNHAPKHO WHERE MAPHIEUNHAP=@MAPHIEUNHAP;
END
GO

IF OBJECT_ID('dbo.SP_THEMPHIEUNHAPKHO','P') IS NOT NULL DROP PROC dbo.SP_THEMPHIEUNHAPKHO;
GO
CREATE PROC dbo.SP_THEMPHIEUNHAPKHO
  @MAPHIEUNHAP CHAR(15), @MASP CHAR(15), @MANCC CHAR(15), @MANV CHAR(15),
  @NGAYLAP DATETIME, @THUEVAT FLOAT
AS
BEGIN
  SET NOCOUNT ON;
  INSERT INTO PHIEUNHAPKHO(MAPHIEUNHAP, MASP, MANCC, MANV, NGAYLAP, THUEVAT)
  VALUES(@MAPHIEUNHAP, @MASP, @MANCC, @MANV, @NGAYLAP, @THUEVAT);
END
GO

IF OBJECT_ID('dbo.SP_SUAPHIEUNHAPKHO','P') IS NOT NULL DROP PROC dbo.SP_SUAPHIEUNHAPKHO;
GO
CREATE PROC dbo.SP_SUAPHIEUNHAPKHO
  @MAPHIEUNHAP CHAR(15), @MASP CHAR(15), @MANCC CHAR(15), @MANV CHAR(15),
  @NGAYLAP DATETIME, @THUEVAT FLOAT
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE PHIEUNHAPKHO
  SET MASP=@MASP, MANCC=@MANCC, MANV=@MANV, NGAYLAP=@NGAYLAP, THUEVAT=@THUEVAT
  WHERE MAPHIEUNHAP=@MAPHIEUNHAP;
END
GO

IF OBJECT_ID('dbo.SP_XOAPHIEUNHAPKHO','P') IS NOT NULL DROP PROC dbo.SP_XOAPHIEUNHAPKHO;
GO
CREATE PROC dbo.SP_XOAPHIEUNHAPKHO @MAPHIEUNHAP CHAR(15)
AS
BEGIN
  SET NOCOUNT ON;
  DELETE FROM PHIEUNHAPKHO WHERE MAPHIEUNHAP=@MAPHIEUNHAP;
END
GO

/* ==== CHI TIET NHAP ==== */
IF OBJECT_ID('dbo.SP_GETCHITIETNHAP','P') IS NOT NULL DROP PROC dbo.SP_GETCHITIETNHAP;
GO
CREATE PROC dbo.SP_GETCHITIETNHAP
AS
BEGIN
  SET NOCOUNT ON;
  SELECT MAPHIEUNHAP, MASP, SOLUONG, DONGIANHAP, THANHTIEN, NGAYNHAPKHO
  FROM CHITIETNHAP;
END
GO

IF OBJECT_ID('dbo.SP_GETCHITIETNHAP_BYPN','P') IS NOT NULL DROP PROC dbo.SP_GETCHITIETNHAP_BYPN;
GO
CREATE PROC dbo.SP_GETCHITIETNHAP_BYPN @MAPHIEUNHAP CHAR(15)
AS
BEGIN
  SET NOCOUNT ON;
  SELECT MAPHIEUNHAP, MASP, SOLUONG, DONGIANHAP, THANHTIEN, NGAYNHAPKHO
  FROM CHITIETNHAP WHERE MAPHIEUNHAP=@MAPHIEUNHAP;
END
GO

IF OBJECT_ID('dbo.SP_GETBYIDCHITIETNHAP','P') IS NOT NULL DROP PROC dbo.SP_GETBYIDCHITIETNHAP;
GO
CREATE PROC dbo.SP_GETBYIDCHITIETNHAP @MAPHIEUNHAP CHAR(15), @MASP CHAR(15)
AS
BEGIN
  SET NOCOUNT ON;
  SELECT MAPHIEUNHAP, MASP, SOLUONG, DONGIANHAP, THANHTIEN, NGAYNHAPKHO
  FROM CHITIETNHAP
  WHERE MAPHIEUNHAP=@MAPHIEUNHAP AND MASP=@MASP;
END
GO

IF OBJECT_ID('dbo.SP_THEMCHITIETNHAP','P') IS NOT NULL DROP PROC dbo.SP_THEMCHITIETNHAP;
GO
CREATE PROC dbo.SP_THEMCHITIETNHAP
  @MAPHIEUNHAP CHAR(15), @MASP CHAR(15), @SOLUONG INT,
  @DONGIANHAP FLOAT, @NGAYNHAPKHO DATETIME
AS
BEGIN
  SET NOCOUNT ON;
  DECLARE @THANHTIEN FLOAT = @SOLUONG * @DONGIANHAP;
  INSERT INTO CHITIETNHAP(MAPHIEUNHAP, MASP, SOLUONG, DONGIANHAP, THANHTIEN, NGAYNHAPKHO)
  VALUES(@MAPHIEUNHAP, @MASP, @SOLUONG, @DONGIANHAP, @THANHTIEN, @NGAYNHAPKHO);
END
GO

IF OBJECT_ID('dbo.SP_SUACHITIETNHAP','P') IS NOT NULL DROP PROC dbo.SP_SUACHITIETNHAP;
GO
CREATE PROC dbo.SP_SUACHITIETNHAP
  @MAPHIEUNHAP CHAR(15), @MASP CHAR(15), @SOLUONG INT,
  @DONGIANHAP FLOAT, @NGAYNHAPKHO DATETIME
AS
BEGIN
  SET NOCOUNT ON;
  DECLARE @THANHTIEN FLOAT = @SOLUONG * @DONGIANHAP;
  UPDATE CHITIETNHAP
  SET SOLUONG=@SOLUONG, DONGIANHAP=@DONGIANHAP, THANHTIEN=@THANHTIEN, NGAYNHAPKHO=@NGAYNHAPKHO
  WHERE MAPHIEUNHAP=@MAPHIEUNHAP AND MASP=@MASP;
END
GO

IF OBJECT_ID('dbo.SP_XOACHITIETNHAP','P') IS NOT NULL DROP PROC dbo.SP_XOACHITIETNHAP;
GO
CREATE PROC dbo.SP_XOACHITIETNHAP @MAPHIEUNHAP CHAR(15), @MASP CHAR(15)
AS
BEGIN
  SET NOCOUNT ON;
  DELETE FROM CHITIETNHAP WHERE MAPHIEUNHAP=@MAPHIEUNHAP AND MASP=@MASP;
END
GO
